### ISSUE TITLE
demo无法使用

### ISSUE THREAD

**Issue by csbz17027** [xu-li/cordova-plugin-wechat-example#11]
我在项目中引入插件发现无法使用后按照您的readMe上所说步骤部署安装了example发现结果相同，
点击各种分享都是返回未知错误，而点击微信授权登录无响应。请问可能是什么原因造成的呢？

**Comment by csbz17027** [comment]
demo中点击“发送文件消息给微信”、“发送gif文件给微信“等与文件相关的选项后会发生crash。
log内容为无法找到文件所引起的空指针异常。

**Comment by xu-li** [comment]
这是正常的。。demo主要还是分享图文信息，登录等，其它功能在android里面都没有实现，所以也不会有功能。

**Comment by csbz17027** [comment]
但是我点击“发送Text消息给微信”也是页面跳转闪一下马上又回到demo页面并弹窗“Failed：未知错误”，而点击“微信授权登录”则无反应。

**Comment by xu-li** [comment]
你的签名什么的都对么？

**Comment by csbz17027** [comment]
发现了，原来不能使用你readme上写的那个appid。需要自己根据demo的数字签名去微信开发者平台配置，然后就可以使用了。是我没理解清楚微信那边的机制，多有打扰了。
再次谢谢您。

**Comment by xu-li** [comment]
没事。关掉了。
