### ISSUE TITLE
发送消息alert“未知错误”

### ISSUE THREAD

**Issue by pinkli** [xu-li/cordova-plugin-wechat-example#18]
按说明安装运行后，点击任何一个“发送消息给微信”，都alert错误信息“未知错误”；
在build的过程中transformClassesWithDexForDebug报一个warning，从官方下载最新的libammsdk.jar覆盖也运行不了。

**Comment by xu-li** [comment]
android的签名不对。

**Comment by pinkli** [comment]
是的，用正确的keystore对应的签名后就正常了。
