### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by pinkli** [xu-li/cordova-plugin-wechat-example#19]
添加IOS平台，通过ionic emulate ios或者用XCode打开，均build失败：
duplicate symbol _llvm.cmdline in:
    /Users/libin/Projects/try-ionic/wechat-example/cordova-plugin-wechat-example/ionic/platforms/ios/Wechat DEMO for cordova.plugin.wechat/Plugins/cordova-plugin-wechat/libWeChatSDK.a(MTAEvent.o)
    /Users/libin/Projects/try-ionic/wechat-example/cordova-plugin-wechat-example/ionic/platforms/ios/Wechat DEMO for cordova.plugin.wechat/Plugins/cordova-plugin-wechat/libWeChatSDK.a(MTAPasteboard.o)

ld: 24 duplicate symbols for architcture x86_64
clang: error: Linker command failed with exit code 1

**Comment by pinkli** [comment]
已解决。
是我所使用的XCode版本问题造成的。
我的XCode版本是6.4, 与1.6.1版的微信sdk不兼容；
编辑plugin.xml，改成使用1.5版的sdk后，编译通过

**Comment by RainyTest** [comment]
我也出现了相同的问题，但是按照你的那个做法改了还是不管用 @pinkli 咋回事呢
