### ISSUE TITLE
cordova.js  Cannot read property 'length'

### ISSUE THREAD

**Issue by shanelisy** [xu-li/cordova-plugin-wechat-example#3]
When I run this demo，I get the following errors:

D/CordovaLog(23450): file:///android_asset/www/cordova.js: Line 914 : Uncaught T
ypeError: Cannot read property 'length' of undefined

What's wrong with that? Please help me, thanks!

**Comment by xu-li** [comment]
The android version is based on the previous version of plugin which is created one year ago. So it might have some unexpected behavior.

I will update the plugin and demo in the coming weeks.

Stay tuned.

**Comment by shanelisy** [comment]
Very expecting...
